### ISSUE TITLE
Why does tcpdump have data, but gor has no data【Version:1.3.0】

### ISSUE THREAD

**Issue by dandyhuang** [probelabs/goreplay#1017]
![image](https://user-images.githubusercontent.com/12603054/136659684-7bd2c8dd-d227-41a2-91c1-e1c5c09b7225.png)

Is my command wrong?

sudo gor --input-raw :13311 --output-file requests.gor

**Comment by dandyhuang** [comment]
sudo gor --input-raw :13311 --input-raw-protocol binary  --output-file ./requests2.gor is ok,need add  --input-raw-protocol binary

**Comment by buger** [comment]
Hi! Yes :)

In general support of binary protocols is part of our PRO version. 
BUT it does not work with all protocols, only some of them, which do not rely too much on state, or some auth.
