### ISSUE TITLE
Gor as a service

### ISSUE THREAD

**Issue by davidvasandani** [probelabs/goreplay#96]
Is anyone running Gor as a service?

**Comment by mosheeshel** [comment]
@dcarley can you elaborate a bit on how to set up with puppet-gor? It says there that you "have to supply your own Gor package" - what does that mean? maybe you can provide a code sample ?
when I used it it doesn't seem to actually install gor on the box.

**Comment by dcarley** [comment]
It will try to install gor from a Debian package in an APT repo using apt-get. We packaged it because it was the easiest and most reliable way to get the same version onto many systems. You could use [fpm](https://github.com/jordansissel/fpm) to do this.

**Comment by mosheeshel** [comment]
Thanks! that helps a lot!
